### ISSUE TITLE
error for BackgroundComponent_Host.ngfactory.js

### ISSUE THREAD

**Issue by behroozbc** [yohaneslumentut/ng-ripple-module#2]
hi 
I a get an error 
![image](https://user-images.githubusercontent.com/20381616/48375809-49cb7980-e6de-11e8-84b6-8d9fd465cd5c.png)

**Comment by behroozbc** [comment]
hi 
I find this error 
![image](https://user-images.githubusercontent.com/20381616/48376462-3caf8a00-e6e0-11e8-868c-1fea8d89267b.png)

**Comment by yohaneslumentut** [comment]
hi.  for 1'st error could you show us your `package.json` at the root of u'r project?

**Comment by yohaneslumentut** [comment]
for the 2'nd error, do the error happened repeatedly? from the error log we got _this.splashPlayer.destroy();  error (line 1120). I forget to validate the existence before destroy the splash animation.

**Comment by behroozbc** [comment]
hi
my package.json 
![image](https://user-images.githubusercontent.com/20381616/48396089-8626c600-e72e-11e8-85c4-989f481385fd.png)
and 2'nd yes its happened repeatedly

**Comment by yohaneslumentut** [comment]
hi
for the 1'st error it's already fix at the new version (0.0.15). Please change line 7 with `"ng-ripple-module":"0.0.15"` then reinstall again with `npm i ng-ripple-module`. For the the second error it's because the lifecycle hook `ngOnDestroy` has been called before the `splashPlayer.onDone` callback. It is happened during change page or during interact with the nest element?

**Comment by behroozbc** [comment]
I update package to 0.0.15 
yes during change page this error happened

**Comment by behroozbc** [comment]
i see this error in 0.0.15 too

**Comment by yohaneslumentut** [comment]
do the 1st error arise in version 0.0.15 ? 2nd error fix haven't finish yet.

**Comment by behroozbc** [comment]
for both question "no"

**Comment by behroozbc** [comment]
I see first error in version 0.0.15

**Comment by yohaneslumentut** [comment]
[prerelease.zip](https://github.com/yohaneslumentut/ng-ripple-module/files/2575574/prerelease.zip)
I don't know what your application behavior. But would you like to download the prerelase file, unzip and put the file in your project root then at the project root run following command in your terminal: `npm install ./ng-ripple-module-0.0.16.tgz` then restart your application server.

**Comment by behroozbc** [comment]
HI 
I INSTALL v 0.0.16 and I see both error again 🤔

**Comment by yohaneslumentut** [comment]
hi,
Please change your package.json with "ng-ripple-module":"0.0.16" then reinstall again with `npm i ng-ripple-module`. if you use ripple in `<a>` tag as navigation button/link, please use `navLink` instead of `href`. Example:
```html
   <a navlink="/home" ripple light
      ...
      (rclick)="goBack($event)"
      (rtap)="goBack($event)">
      Back
   </a>
```
```ts
   ...
   import  { Router } from '@angular/router';
   ...
   export default SecondPage {
      ...
      constructor(private router: Router) { 
         ... 
      }
      ...
      goBack(event: any) {
         this.router.navigateByUrl(event.navLink);
      }
      ...
   }
```
I've test in my angular app and ionic 3 app, and found no more error. would you like to test to your app too?

**Comment by yohaneslumentut** [comment]
hi,
please install the latest version (v.0.0.17) and I hope your problem will be solved by the latest version.
I close this issue. If you find that the bug still arise at the latest version, please reopen this issue again.
Thanks
